
---

## 🔹 GitHub Actions Workflow: `.github/workflows/02-vpc-networking.yml`

```yaml
name: 02 - VPC Networking

on:
  push:
    paths:
      - '02-vpc-networking/**'
  pull_request:
    paths:
      - '02-vpc-networking/**'

jobs:
  terraform:
    name: Apply Terraform in 02-vpc-networking/
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.0

      - name: Terraform Init
        working-directory: 02-vpc-networking
        run: terraform init

      - name: Terraform Plan
        working-directory: 02-vpc-networking
        run: terraform plan

      - name: Terraform Apply
        working-directory: 02-vpc-networking
        run: terraform apply -auto-approve
