name: 04 - RDS PostgreSQL

on:
  push:
    paths:
      - '04-rds-postgres/**'
      - '.github/workflows/04-rds-postgres.yml'

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 04-rds-postgres

    env:
      EC2_SECURITY_GROUP_ID: ${{ secrets.EC2_SECURITY_GROUP_ID }}
      RDS_SECURITY_GROUP_ID: ${{ secrets.RDS_SECURITY_GROUP_ID }}
      PRIVATE_SUBNET_IDS: ${{ secrets.PRIVATE_SUBNET_IDS }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="ec2_security_group_id=${EC2_SECURITY_GROUP_ID}" \
            -var="rds_security_group_id=${RDS_SECURITY_GROUP_ID}" \
            -var="private_subnet_ids=${PRIVATE_SUBNET_IDS}" \
            -var="db_password=${DB_PASSWORD}"

      - name: Terraform Apply (auto-approve)
        if: github.ref == 'refs/heads/main'
        run: |
          terraform apply -auto-approve \
            -var="ec2_security_group_id=${EC2_SECURITY_GROUP_ID}" \
            -var="rds_security_group_id=${RDS_SECURITY_GROUP_ID}" \
            -var="private_subnet_ids=${PRIVATE_SUBNET_IDS}" \
            -var="db_password=${DB_PASSWORD}"
